project_name: wx
release:
  github:
    owner: wxio
    name: wx
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - "386"
  ignore:
  - goos: linux
    goarch: "386"
  - goos: darwin
    goarch: "386"
  main: .
  ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: wx
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
  - .wx*
